project_id = "bbkhiwrgqilaokowhtxg"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-builder]
verify_jwt = false

[functions.fetch-tiktok-data]
verify_jwt = false

[functions.search-tiktok]
verify_jwt = false